
!!org.fish.appium.entity.ConfigEntity
account:
- {name: Name, password: Password, username: 'Username'}
applicationActivity: com.alibaba.android.rimet.biz.LaunchHomeActivity
applicationPackage: com.alibaba.android.rimet
deviceName: Android
devicePlatform: Android
deviceVersion: '10'
noReset: true
timeout: 20
udid: Z81QAEYPA725H
url: http://127.0.0.1:4723/wd/hub
wait: 10
